// ProductData.js:

const Data = [
  {
    id: 1,
    title: "Apple iPhone 12 Pro",
    price: 999,
    specifications: "6.1-inch Super Retina XDR display",
    colors: "Blue, Gold, Graphite, Silver",
    storage: "128GB, 256GB, 512GB",
    image: "https://source.unsplash.com/1600x900/?iphone",
  },
  {
    id: 2,
    title: "Apple iPhone 12",
    price: 799,
    specifications: "6.1-inch Super Retina XDR display",
    colors: "Blue, Green, Red, White, Black",
    storage: "64GB, 128GB, 256GB",
    image: "https://source.unsplash.com/1600x900/?iphone",
  },
  {
    id: 3,
    title: "Apple iPhone 11",
    price: 599,
    specifications: "6.1-inch Liquid Retina HD display",
    colors: "Purple, Yellow, Green, Black, White, Red",
    storage: "64GB, 128GB, 256GB",
    image: "https://source.unsplash.com/1600x900/?iphone",
  },
  {
    id: 4,
    title: "Apple iPhone SE",
    price: 399,
    specifications: "4.7-inch Retina HD display",
    colors: "Black, White, Red",
    storage: "64GB, 128GB, 256GB",
    image: "https://source.unsplash.com/1600x900/?iphone",
  },
  // google phone
  {
    id: 5,
    title: "Google Pixel 5",
    price: 699,
    specifications: "6.0-inch FHD+ OLED display",
    colors: "Just Black, Sorta Sage",
    storage: "128GB",
    image: "https://source.unsplash.com/1600x900/?google",
  },
  {
    id: 6,
    title: "Google Pixel 4a",
    price: 349,
    specifications: "5.81-inch FHD+ OLED display",
    colors: "Just Black",
    storage: "128GB",
    image: "https://source.unsplash.com/1600x900/?google",
  },
  {
    id: 7,
    title: "Google Pixel 4",
    price: 799,
    specifications: "5.7-inch FHD+ OLED display",
    colors: "Just Black, Clearly White, Oh So Orange",
    storage: "64GB, 128GB",
    image: "https://source.unsplash.com/1600x900/?google",
  },
  {
    id: 8,
    title: "Google Pixel 3a",
    price: 399,
    specifications: "5.6-inch FHD+ OLED display",
    colors: "Just Black, Clearly White, Purple-ish",
    storage: "64GB",
    image: "https://source.unsplash.com/1600x900/?google",
  },
  // samsung phone
  {
    id: 9,
    title: "Samsung Galaxy S21 Ultra",
    price: 1199,
    specifications: "6.8-inch Dynamic AMOLED 2X display",
    colors: "Phantom Black, Phantom Silver, Phantom Titanium, Phantom Navy",
    storage: "128GB, 256GB, 512GB",
    image: "https://source.unsplash.com/1600x900/?samsung",
  },
  {
    id: 10,
    title: "Samsung Galaxy S21+",
    price: 999,
    specifications: "6.7-inch Dynamic AMOLED 2X display",
    colors: "Phantom Black, Phantom Silver, Phantom Violet",
    storage: "128GB, 256GB",
    image: "https://source.unsplash.com/1600x900/?samsung",
  },
  {
    id: 11,
    title: "Samsung Galaxy S21",
    price: 799,
    specifications: "6.2-inch Dynamic AMOLED 2X display",
    colors: "Phantom Gray, Phantom White, Phantom Violet, Phantom Pink",
    storage: "128GB, 256GB",
    image: "https://source.unsplash.com/1600x900/?samsung",
  },
  {
    id: 12,
    title: "Samsung Galaxy S20 FE",
    price: 699,
    specifications: "6.5-inch Super AMOLED display",
    colors:
      "Cloud Red, Cloud Orange, Cloud Lavender, Cloud Mint, Cloud Navy, Cloud White",
    storage: "128GB",
    image: "https://source.unsplash.com/1600x900/?samsung",
  },
];

export default Data;
